In [2]:
import pandas as pd
data = {
    'Name': ["Alice","Bob","Charlie"],
    'Age': [25,30,35]
}
s = pd.DataFrame(data)
s

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [2]:
import pandas as pd
data = {
'Student': ['Ali', 'Zain', 'Sara'],
'GPA': [3.8, 3.2, 3.9],
'City': ['Lahore', 'Karachi', 'Islamabad']
}
df = pd.DataFrame(data)
df

  Student  GPA       City
0     Ali  3.8     Lahore
1    Zain  3.2    Karachi
2    Sara  3.9  Islamabad

Selection & Indexing

In [4]:
import pandas as pd
data = {
    "Name": ["ALi","Sara","Ahsan","Zara","Usman","Hina","Bilal","Ayesha"],
    "Age": [21,23,20,22,24,21,23,22],
    "City": ["Lahore","Karachi","Lahore","Islamabad","Karachi","Lahore","Islamabad","Karachi"],
    "Marks": [85,90,78,92,88,76,95,89]
}
df = pd.DataFrame(data)
print(df)

     Name  Age       City  Marks
0     ALi   21     Lahore     85
1    Sara   23    Karachi     90
2   Ahsan   20     Lahore     78
3    Zara   22  Islamabad     92
4   Usman   24    Karachi     88
5    Hina   21     Lahore     76
6   Bilal   23  Islamabad     95
7  Ayesha   22    Karachi     89

In [5]:
print(df["Name"]) # select single column

0       ALi
1      Sara
2     Ahsan
3      Zara
4     Usman
5      Hina
6     Bilal
7    Ayesha
Name: Name, dtype: object

In [6]:
print(df["Age"])
print(df["City"])  # multiple columns

0    21
1    23
2    20
3    22
4    24
5    21
6    23
7    22
Name: Age, dtype: int64
0       Lahore
1      Karachi
2       Lahore
3    Islamabad
4      Karachi
5       Lahore
6    Islamabad
7      Karachi
Name: City, dtype: object

In [6]:
print(df[["Name","Marks"]]) # select multiple column

     Name  Marks
0     ALi     85
1    Sara     90
2   Ahsan     78
3    Zara     92
4   Usman     88
5    Hina     76
6   Bilal     95
7  Ayesha     89

In [7]:
print(df.loc[0]) # select single row

Name        ALi
Age          21
City     Lahore
Marks        85
Name: 0, dtype: object

In [8]:
print(df.loc[0:2]) #select multiple row

    Name  Age     City  Marks
0    ALi   21   Lahore     85
1   Sara   23  Karachi     90
2  Ahsan   20   Lahore     78

In [9]:
print(df.loc[0:3, ['Name','Marks']]) # select ros + specific columns

    Name  Marks
0    ALi     85
1   Sara     90
2  Ahsan     78
3   Zara     92

In [10]:
print(df.loc[df["Marks"] > 85]) #condition filtering with iloc

     Name  Age       City  Marks
1    Sara   23    Karachi     90
3    Zara   22  Islamabad     92
4   Usman   24    Karachi     88
6   Bilal   23  Islamabad     95
7  Ayesha   22    Karachi     89

In [11]:
print(df.iloc[0]) #use index position numbers (first row)

Name        ALi
Age          21
City     Lahore
Marks        85
Name: 0, dtype: object

In [12]:
print(df.iloc[0:3])#firs 3 rows

    Name  Age     City  Marks
0    ALi   21   Lahore     85
1   Sara   23  Karachi     90
2  Ahsan   20   Lahore     78

In [13]:
print(df.iloc[0:3, 0:2]) #rows + column based

    Name  Age
0    ALi   21
1   Sara   23
2  Ahsan   20

In [14]:
print(df.at[2, "Name"]) #These are faster when accessing single value.

Ahsan

In [15]:
print(df.iat[2, 0])

Ahsan

In [ ]:
print(df.query("Marks > 85")) #filter using sql like syntax

     Name  Age       City  Marks
1    Sara   23    Karachi     90
3    Zara   22  Islamabad     92
4   Usman   24    Karachi     88
6   Bilal   23  Islamabad     95
7  Ayesha   22    Karachi     89

In [17]:
print(df.query("Marks > 85 and City == 'Karachi'")) #mulltile connditions

     Name  Age     City  Marks
1    Sara   23  Karachi     90
4   Usman   24  Karachi     88
7  Ayesha   22  Karachi     89

In [18]:
print(df.filter(items = ["Name","City"])) #filter columns by names

     Name       City
0     ALi     Lahore
1    Sara    Karachi
2   Ahsan     Lahore
3    Zara  Islamabad
4   Usman    Karachi
5    Hina     Lahore
6   Bilal  Islamabad
7  Ayesha    Karachi

In [19]:
print(df.filter(like="Ma")) # matches "Marks"

   Marks
0     85
1     90
2     78
3     92
4     88
5     76
6     95
7     89

In [20]:
print(df.filter(items=[0,1,2], axis=0)) #Filter rows by index

    Name  Age     City  Marks
0    ALi   21   Lahore     85
1   Sara   23  Karachi     90
2  Ahsan   20   Lahore     78