Inspecting Data

In [1]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Ali","Sara","Ahmed","Zara","Usman","Hina","Bilal","Ayesha"],
    "Age": [21,23,20,22,24,21,23,22],
    "City": ["Lahore","Karachi","Lahore","Islamabad","Karachi","Lahore","Islamabad","Karachi"],
    "Marks": [85,90,78,92,88,76,95,89]
}

df = pd.DataFrame(data)
print(df)

     Name  Age       City  Marks
0     Ali   21     Lahore     85
1    Sara   23    Karachi     90
2   Ahmed   20     Lahore     78
3    Zara   22  Islamabad     92
4   Usman   24    Karachi     88
5    Hina   21     Lahore     76
6   Bilal   23  Islamabad     95
7  Ayesha   22    Karachi     89

In [4]:
df.head()

    Name  Age       City  Marks
0    Ali   21     Lahore     85
1   Sara   23    Karachi     90
2  Ahmed   20     Lahore     78
3   Zara   22  Islamabad     92
4  Usman   24    Karachi     88

In [5]:
df.head(3)

    Name  Age     City  Marks
0    Ali   21   Lahore     85
1   Sara   23  Karachi     90
2  Ahmed   20   Lahore     78

In [6]:
df.tail()

     Name  Age       City  Marks
3    Zara   22  Islamabad     92
4   Usman   24    Karachi     88
5    Hina   21     Lahore     76
6   Bilal   23  Islamabad     95
7  Ayesha   22    Karachi     89

In [7]:
df.tail(2)

     Name  Age       City  Marks
6   Bilal   23  Islamabad     95
7  Ayesha   22    Karachi     89