Inspecting Data

In [1]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Ali","Sara","Ahmed","Zara","Usman","Hina","Bilal","Ayesha"],
    "Age": [21,23,20,22,24,21,23,22],
    "City": ["Lahore","Karachi","Lahore","Islamabad","Karachi","Lahore","Islamabad","Karachi"],
    "Marks": [85,90,78,92,88,76,95,89]
}

df = pd.DataFrame(data)
print(df)

     Name  Age       City  Marks
0     Ali   21     Lahore     85
1    Sara   23    Karachi     90
2   Ahmed   20     Lahore     78
3    Zara   22  Islamabad     92
4   Usman   24    Karachi     88
5    Hina   21     Lahore     76
6   Bilal   23  Islamabad     95
7  Ayesha   22    Karachi     89

In [ ]:
df.head()   #shows first 5 rows

    Name  Age       City  Marks
0    Ali   21     Lahore     85
1   Sara   23    Karachi     90
2  Ahmed   20     Lahore     78
3   Zara   22  Islamabad     92
4  Usman   24    Karachi     88

In [ ]:
df.head(3)  # first 3 rows

    Name  Age     City  Marks
0    Ali   21   Lahore     85
1   Sara   23  Karachi     90
2  Ahmed   20   Lahore     78

In [ ]:
df.tail()   #shows last rows

     Name  Age       City  Marks
3    Zara   22  Islamabad     92
4   Usman   24    Karachi     88
5    Hina   21     Lahore     76
6   Bilal   23  Islamabad     95
7  Ayesha   22    Karachi     89

In [ ]:
df.tail(2)  #last 2 rows

     Name  Age       City  Marks
6   Bilal   23  Islamabad     95
7  Ayesha   22    Karachi     89

In [ ]:
df.sample() # random row from dataset

    Name  Age       City  Marks
6  Bilal   23  Islamabad     95

In [10]:
df.sample(2) # random two rows

    Name  Age       City  Marks
3   Zara   22  Islamabad     92
2  Ahmed   20     Lahore     78

In [11]:
df.info() # gives full info of dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    8 non-null      object
 1   Age     8 non-null      int64
 2   City    8 non-null      object
 3   Marks   8 non-null      int64
dtypes: int64(2), object(2)
memory usage: 388.0+ bytes

In [12]:
df.describe() # statistical summary (numeric columns)

             Age      Marks
count   8.000000   8.000000
mean   22.000000  86.625000
std     1.309307   6.631903
min    20.000000  76.000000
25%    21.000000  83.250000
50%    22.000000  88.500000
75%    23.000000  90.500000
max    24.000000  95.000000

In [13]:
df.describe(include = "all") #include all columns

       Name        Age    City      Marks
count     8   8.000000       8   8.000000
unique    8        NaN       3        NaN
top     Ali        NaN  Lahore        NaN
freq      1        NaN       3        NaN
mean    NaN  22.000000     NaN  86.625000
std     NaN   1.309307     NaN   6.631903
min     NaN  20.000000     NaN  76.000000
25%     NaN  21.000000     NaN  83.250000
50%     NaN  22.000000     NaN  88.500000
75%     NaN  23.000000     NaN  90.500000
max     NaN  24.000000     NaN  95.000000

In [15]:
df.shape # returns rows & columns

(8, 4)

In [16]:
df.columns # show columns names

Index(['Name', 'Age', 'City', 'Marks'], dtype='object')

In [17]:
print(list(df.columns)) #convert to list

['Name', 'Age', 'City', 'Marks']

In [18]:
df.index #  show row index

RangeIndex(start=0, stop=8, step=1)

In [19]:
df.dtypes # show datatype of each column

Name     object
Age       int64
City     object
Marks     int64
dtype: object

In [20]:
df.nunique() # counts unique values in each column

Name     8
Age      5
City     3
Marks    8
dtype: int64

In [ ]:
df.value_counts() # value counts of row column

Name    Age  City       Marks
Ahmed   20   Lahore     78       1
Ali     21   Lahore     85       1
Ayesha  22   Karachi    89       1
Bilal   23   Islamabad  95       1
Hina    21   Lahore     76       1
Sara    23   Karachi    90       1
Usman   24   Karachi    88       1
Zara    22   Islamabad  92       1
Name: count, dtype: int64

In [22]:
df["City"].value_counts() # value counts of specific column

City
Lahore       3
Karachi      3
Islamabad    2
Name: count, dtype: int64

Data cleaning

In [1]:
import pandas as pd
import numpy as np
data = {
    "Name": ["Ali","Sara","Ahmed","Zara","Ali","Hina",np.nan],
    "Age": [21,23,20,22,21,np.nan,24],
    "City": ["Lahore","Karachi","Lahore","Islamabad","Lahore","Lahore","Karachi"],
    "Marks": [85,90,78,92,85,76,np.nan]
}
df = pd.DataFrame(data)
df

    Name   Age       City  Marks
0    Ali  21.0     Lahore   85.0
1   Sara  23.0    Karachi   90.0
2  Ahmed  20.0     Lahore   78.0
3   Zara  22.0  Islamabad   92.0
4    Ali  21.0     Lahore   85.0
5   Hina   NaN     Lahore   76.0
6    NaN  24.0    Karachi    NaN

In [2]:
df1 = df.drop("City",axis = 1)
print(df1)

    Name   Age  Marks
0    Ali  21.0   85.0
1   Sara  23.0   90.0
2  Ahmed  20.0   78.0
3   Zara  22.0   92.0
4    Ali  21.0   85.0
5   Hina   NaN   76.0
6    NaN  24.0    NaN

In [3]:
df1 = df.drop(["City","Marks"],axis = 1)
df1

    Name   Age
0    Ali  21.0
1   Sara  23.0
2  Ahmed  20.0
3   Zara  22.0
4    Ali  21.0
5   Hina   NaN
6    NaN  24.0

In [4]:
df1 = df.drop(0)
df1

    Name   Age       City  Marks
1   Sara  23.0    Karachi   90.0
2  Ahmed  20.0     Lahore   78.0
3   Zara  22.0  Islamabad   92.0
4    Ali  21.0     Lahore   85.0
5   Hina   NaN     Lahore   76.0
6    NaN  24.0    Karachi    NaN

In [5]:
df1 = df.drop_duplicates()
df1

    Name   Age       City  Marks
0    Ali  21.0     Lahore   85.0
1   Sara  23.0    Karachi   90.0
2  Ahmed  20.0     Lahore   78.0
3   Zara  22.0  Islamabad   92.0
5   Hina   NaN     Lahore   76.0
6    NaN  24.0    Karachi    NaN

In [6]:
df1 = df.drop_duplicates(subset = "Name")
df1

    Name   Age       City  Marks
0    Ali  21.0     Lahore   85.0
1   Sara  23.0    Karachi   90.0
2  Ahmed  20.0     Lahore   78.0
3   Zara  22.0  Islamabad   92.0
5   Hina   NaN     Lahore   76.0
6    NaN  24.0    Karachi    NaN

In [7]:
df1 = df.rename(columns={"Marks":"Score"})
df1

    Name   Age       City  Score
0    Ali  21.0     Lahore   85.0
1   Sara  23.0    Karachi   90.0
2  Ahmed  20.0     Lahore   78.0
3   Zara  22.0  Islamabad   92.0
4    Ali  21.0     Lahore   85.0
5   Hina   NaN     Lahore   76.0
6    NaN  24.0    Karachi    NaN

In [8]:
df1 = df.rename(columns={"Name":"Student","Age":"Years"})
df1

  Student  Years       City  Marks
0     Ali   21.0     Lahore   85.0
1    Sara   23.0    Karachi   90.0
2   Ahmed   20.0     Lahore   78.0
3    Zara   22.0  Islamabad   92.0
4     Ali   21.0     Lahore   85.0
5    Hina    NaN     Lahore   76.0
6     NaN   24.0    Karachi    NaN

In [9]:
df1 = df.replace("Lahore","LHR")
df1

    Name   Age       City  Marks
0    Ali  21.0        LHR   85.0
1   Sara  23.0    Karachi   90.0
2  Ahmed  20.0        LHR   78.0
3   Zara  22.0  Islamabad   92.0
4    Ali  21.0        LHR   85.0
5   Hina   NaN        LHR   76.0
6    NaN  24.0    Karachi    NaN

In [10]:
df1 = df.replace({"Lahore":"LHR","Karachi":"KHI"})
df1

    Name   Age       City  Marks
0    Ali  21.0        LHR   85.0
1   Sara  23.0        KHI   90.0
2  Ahmed  20.0        LHR   78.0
3   Zara  22.0  Islamabad   92.0
4    Ali  21.0        LHR   85.0
5   Hina   NaN        LHR   76.0
6    NaN  24.0        KHI    NaN

In [12]:
df1 = df.fillna(0)
df1

    Name   Age       City  Marks
0    Ali  21.0     Lahore   85.0
1   Sara  23.0    Karachi   90.0
2  Ahmed  20.0     Lahore   78.0
3   Zara  22.0  Islamabad   92.0
4    Ali  21.0     Lahore   85.0
5   Hina   0.0     Lahore   76.0
6      0  24.0    Karachi    0.0

In [13]:
df1 = df.copy()
df1["Age"] = df1["Age"].fillna(df1["Age"].mean())
df1

    Name        Age       City  Marks
0    Ali  21.000000     Lahore   85.0
1   Sara  23.000000    Karachi   90.0
2  Ahmed  20.000000     Lahore   78.0
3   Zara  22.000000  Islamabad   92.0
4    Ali  21.000000     Lahore   85.0
5   Hina  21.833333     Lahore   76.0
6    NaN  24.000000    Karachi    NaN